class SlackNotificationService
  def initialize(webhook_url)
    @webhook_url = webhook_url
  end

  # Posts a standup summary to Slack. Returns true on success, raises on failure.
  def post_summary(summary)
    return false if @webhook_url.blank?

    date_str = summary.summary_date.strftime("%A, %B %-d")
    payload = {
      text: ":spiral_note_pad: *Standup Summary — #{date_str}*",
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: ":spiral_note_pad: Standup Summary — #{date_str}",
            emoji: true
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: truncate_for_slack(summary.content)
          }
        },
        {
          type: "context",
          elements: [
            {
              type: "mrkdwn",
              text: "#{summary.entry_count} team member(s) submitted • Generated by Standup Bot"
            }
          ]
        }
      ]
    }

    conn = Faraday.new do |f|
      f.request :json
      f.response :raise_error
    end

    conn.post(@webhook_url, payload)
    true
  end

  private

  # Slack blocks have a 3000-char limit per text field
  def truncate_for_slack(text, limit = 2900)
    return text if text.length <= limit

    text[0, limit] + "\n\n_[Summary truncated — see full version in the app]_"
  end
end
